export enum StackScreenName {
  // splashScreen = 'SplashScreen',
  landing = 'Landing',
  welcome = 'Welcome',
  registration = 'Registration',
  avatar = 'Avatar',
  linkGame = 'LinkGame',
  googleModal = 'GoogleModal',
  steamLogin = 'SteamLogin',
  steamModal = 'SteamModal',
  steamLink = 'SteamLink',
  home = 'Home',
  allLeagues = 'AllLeagues',
  leagueInfo = 'LeagueInfo',
}
